### ISSUE TITLE
how to create subscription?

### ISSUE THREAD

**Issue by khanhtq** [CyberSource/cybersource-sdk-php#12]

**Comment by djvaldez** [comment]
Hi @khanhtq, to create a subscription, you can modify one of the samples to include something like the code below. We'll have a sample like this included shortly.

```php
$referenceCode = 'your_merchant_reference_code';

$client = new CybsSoapClient();
$request = $client->createRequest($referenceCode);

$paySubscriptionCreateService = new stdClass();
$paySubscriptionCreateService->run = 'true';
$request->paySubscriptionCreateService = $paySubscriptionCreateService;

$billTo = new stdClass();
$billTo->firstName = 'John';
$billTo->lastName = 'Doe';
$billTo->street1 = '1295 Charleston Road';
$billTo->city = 'Mountain View';
$billTo->state = 'CA';
$billTo->postalCode = '94043';
$billTo->country = 'US';
$billTo->email = 'null@cybersource.com';
$billTo->ipAddress = '10.7.111.111';
$request->billTo = $billTo;

$card = new stdClass();
$card->accountNumber = '4111111111111111';
$card->expirationMonth = '12';
$card->expirationYear = '2020';
$card->cardType='001';
$request->card = $card;

$purchaseTotals = new stdClass();
$purchaseTotals->currency = 'USD';
$request->purchaseTotals = $purchaseTotals;

$recurringSubscriptionInfo = new stdClass();
$recurringSubscriptionInfo->frequency = 'monthly';
$recurringSubscriptionInfo->amount = '11.00';
$recurringSubscriptionInfo->automaticRenew = 'false';
$recurringSubscriptionInfo->numberOfPayments = '4';
$recurringSubscriptionInfo->startDate = '20140221';

$request->recurringSubscriptionInfo = $recurringSubscriptionInfo;

$reply = $client->runTransaction($request);
```

**Comment by khanhtq** [comment]
Thank you,
Before ask question, I did similiar to your guide, but met an error with reasonCode 150, I don't know where was wrong. I do follow your example but still has this error.
This is return data when execute Subscription.php:
<pre>
SUBSCRIPTION RESPONSE: stdClass Object
(
    [requestID] => 4213814903580176195843
    [decision] => ERROR
    [reasonCode] => 150
    [requestToken] => Ahj/7wSRyNzbsh2umUIGIkGTJu4csnDGc0sVKEppQT+DC0KOwBT+DC0KOzSACcuABpJli6+B6eECcjkbm3ZDtdMoQMAACw6+
    [ccAuthReply] => stdClass Object
        (
            [reasonCode] => 100
            [amount] => 0.00
            [authorizationCode] => 888888
            [avsCode] => X
            [avsCodeRaw] => I1
            [authorizedDateTime] => 2015-01-16T04:11:30Z
            [processorResponse] => 100
            [reconciliationID] => 22789281N4XTPJ4P
        )

    [paySubscriptionCreateReply] => stdClass Object
        (
            [reasonCode] => 150
        )

)
Failed subscription request.
</pre>


Notice: 2 examples of  AuthFollowOnCapture.php and Sale.php are working normal, does Subscription feature support test enviroment? Waiting for your help, thank you.

**Comment by brianmc** [comment]
Subscription is not on by default in the sandbox so that is something we will get fixed.  In the short term, if you send your MID (merchant ID) to developer@cybersource.com we can enable subscriptions on that account.

Thanks for the feedback.

**Comment by khanhtq** [comment]
Thank @djvaldez very much

**Comment by bhanwarpsrathore** [comment]
@brianmc  Is **Subscription is not on by default in the sandbox so that is something we will get fixed** is fixed, I am having the same issue @khanhtq  faced, I also sent mail to @developer@cybersource.com. How long you guys take to enable this.
