### ISSUE TITLE
Error - General system failure (150)

### ISSUE THREAD

**Issue by ipanardian** [CyberSource/cybersource-sdk-php#24]
The merchant_id and transaction keys has been setup properly. But when i create transaction response from cybersource is General system failure (150). What is missing? thanks

**Comment by aqabawe** [comment]
Hello, I was getting a `Payment processor error This field is invalid or missing. Please contact customer support.: merchant_id` on our Ruby implementation of Secure Acceptance.

The reason turned out to be that we were using a currency that was not supported by our account.

**Comment by juniormc** [comment]
@aqabawe Thanks, working for me!.
