### ISSUE TITLE
Payment Tokenization

### ISSUE THREAD

**Issue by fiatux** [CyberSource/cybersource-sdk-php#26]
Does this SDK support payment tokenization?

**Comment by amie-gao** [comment]
the SDK has samples which demo how to use network payment token, apple pay, android pay and visa checkout.

**Comment by fiatux** [comment]
@amie-gao no actually, I am looking for a method to save credit card on cybersource and then use it in a transaction by its token. all samples in the sdk use credit card information directly.

**Comment by amie-gao** [comment]
@fiatux I see. we have not implemented the CYBS token management service in the SDK yet.

**Comment by amie-gao** [comment]
@fiatux also, you can refer to our [Flex Samples](https://github.com/CyberSource/cybersource-flex-samples)  to see if that helps.

**Comment by muratsac** [comment]
@payconn

**Comment by sivajik34** [comment]
@amie-gao  any update on this?
